version: "3.8"

services:
  api:
    image: boltcola/solana-balance-api:latest
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - solana-net
    depends_on:
      - mongo

  mongo:
    image: mongo
    networks:
      - solana-net
    volumes:
      - mongo-data:/data/db

networks:
  solana-net:

volumes:
  mongo-data:
